### ISSUE TITLE
console.log doesn't seem to work

### ISSUE THREAD

**Issue by timoxley** [BarkingMouseStudio/try-coffeescript-chrome#1]
tried running this simple script using the try coffeescript button: 

```
console.log "test"
```

but I don't see any output appearing in my console. 
What's up with that? Is there another console it's going to?

**Comment by jimfleming** [comment]
Chrome extensions are basically self-contained web pages so its output is directed to its own console.

If you enable developer mode by going to the url chrome://extensions you can then right click on the Try CoffeeScript button and click "Inspect Popup". From here you can see the console.log output.

I know this is probably not what you're hoping to do but if you figure out a way to redirect the console output I'm happy to implement it.

**Comment by timoxley** [comment]
Thanks.  Perhaps the solution would be to either override the built-in console object (and provide your own implementation) or provide some other debugging mechanism that just provides some value printing ability. Never done an extension, so I have no idea how easy or hard that would be.
